import { Address } from './Address';
import { Billing } from './Billing';
import { Card } from './Card';
import { Customer } from './Customer';
import { Item } from './Item';
import { Shipping } from './Shipping';

export interface Transaction {
  object: string;
  status: string;
  refuse_reason: string;
  status_reason: string;
  acquirer_name: string;
  acquirer_id: string;
  acquirer_response_code: string;
  authorization_code: string;
  soft_descriptor: string;
  tid: number;
  nsu: number;
  date_created: string;
  date_updated: string;
  amount: number;
  authorized_amount: number;
  paid_amount: number;
  refunded_amount: number;
  installments: number;
  id: number;
  cost: number;
  card_holder_name: string;
  card_last_digits: string;
  card_first_digits: string;
  card_brand: string;
  card_pin_mode: string;
  postback_url: string;
  payment_method: string;
  capture_method: string;
  antifraud_score: string;
  boleto_url: string;
  boleto_barcode: string;
  boleto_expiration_date: string;
  referer: string;
  ip: string;
  subscription_id: string;
  customer: Customer;
  billing: Billing;
  shipping: Shipping;
  items: Item[];
  address: Address;
  card: Card;
  split_rules: any;
  metadata: any;
  antifraud_metadata: any;
  reference_key: string;
}
